id: IC8E1CE28
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:05:49+00:00'
last_modified: '2022-06-08T10:32:44.925070+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09673
  title: ཕྱག་ཆེན་ལྷན་ཅིག་སྐྱེས་སྦྱོར་གྱི་ངོ་སྤྲོད་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FB77:
      image_group_id: I00KG09679
      title: ''
      total_pages: 44
      order: 1
      base_file: FB77.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
