id: P009372
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:35:42.518608
source_metadata:
  id: bdr:W00KG09673
  title: ཕྱག་ཆེན་ལྷན་ཅིག་སྐྱེས་སྦྱོར་གྱི་ངོ་སྤྲོད་
  author: ''
  volumes:
    6ab144777d954e6580376191b8057da9:
      image_group_id: I00KG09679
      title: ''
      volume_number: 1
      total_pages: 44
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
