id: P009372
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09673
  title: ཕྱག་ཆེན་ལྷན་ཅིག་སྐྱེས་སྦྱོར་གྱི་ངོ་སྤྲོད་
  author: ''
  volumes:
    6ab144777d954e6580376191b8057da9:
      image_group_id: I00KG09679
      title: ''
      volume_number: 1
      total_pages: 44
